AWSTemplateFormatVersion: 2010-09-09
Description: |
  Akitten carousel website, including ec2 instance and security group
  
Resources:

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80  
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22  
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-041feb57c611358bd
      InstanceType: "t2.micro"
      KeyName: aws_practice_keypair
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      Tags: 
        - Key: Name
          Value: Gulsah Kittens Web Server
      UserData: 
        Fn::Base64:
          |
            #! /bin/bash -x
            yum update -y
            yum install httpd -y
            cd /var/www/html
            FOLDER="https://raw.githubusercontent.com/hgulsah/aws14_projects/main/101-kittens-carousel-static-website-ec2/static-web/"
            wget ${FOLDER}index.html
            wget ${FOLDER}cat0.jpg
            wget ${FOLDER}cat1.jpg
            wget ${FOLDER}cat2.jpg
            systemctl start httpd
            systemctl enable httpd
